# This is an example `emlop` config file.
#
# It is loaded from `$HOME/.config/emlop.toml` by default.
# Use `$EMLOP_CONFIG` to set a different location, empty string to disable config loading.
#
# Entries have the same name and format as command-line args, see `emlop <command> --help`.
# Some args are only avaible via the command line.

# logfile = "/var/log/emerge.log"
# date = "rfc2822"
# duration = "human"
# utc = true
# header = true
# color = "yes"
# theme = "merge:1;32 binmerge:0;32 unmerge:1;31 sync:1;36 duration:1;35 count:0;33 qmark:0 skip:3;37"
# output = "columns"
# showskip = true
[log]
# show = "mus"
# starttime = true
[predict]
# show = "emt"
# avg = "arith"
# limit = 20
# unknownb = 30
# unknownc = 10
# tmpdir = ["/foo", "/bar"]
# mtimedbfile = "/var/cache/edb/mtimedb"
# pwidth = 60
# pdepth = 3
[stats]
# show = "pts"
# avg = "arith"
# limit = 20
# group = "y"
[accuracy]
# show = "mt"
# avg = "arith"
# limit = 20
